DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE;

DROP SEQUENCE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE IF EXISTS BATCH_JOB_SEQ;

DROP TABLE IF EXISTS EVENT_PUBLICATION;
DROP TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY;

DROP TABLE IF EXISTS MF_RETURN_STATS;
DROP TABLE IF EXISTS MF_SCHEME_NAV;
DROP TABLE IF EXISTS MF_SCHEME_DETAILS;
DROP TABLE IF EXISTS MF_FUND_HOUSE;

DROP SEQUENCE IF EXISTS MF_RETURN_STATS_SEQ;
DROP SEQUENCE IF EXISTS MF_SCHEME_DETAILS_SEQ;
DROP SEQUENCE IF EXISTS MF_SCHEME_NAV_SEQ;