spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/indfinvestor
    username: finvestor
    password: finvestor
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/{vendor}
  batch:
    jdbc:
      initialize-schema: never
