CREATE SEQUENCE IF NOT EXISTS mf_return_stats_seq START WITH 1 INCREMENT BY 100;

CREATE SEQUENCE IF NOT EXISTS mf_scheme_details_seq START WITH 1 INCREMENT BY 10;

CREATE SEQUENCE IF NOT EXISTS mf_scheme_nav_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE mf_fund_house
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_mf_fund_house PRIMARY KEY (id)
);

CREATE TABLE mf_return_stats
(
    id             BIGINT         NOT NULL,
    year_nos       BIGINT         NOT NULL,
    std_dev        numeric(10, 2),
    mean           numeric(10, 2),
    percentile_90  numeric(10, 2),
    percentile_95  numeric(10, 2),
    negative_count numeric(10, 2) NOT NULL,
    count_5        numeric(10, 2) NOT NULL,
    count_10       numeric(10, 2) NOT NULL,
    count_15       numeric(10, 2) NOT NULL,
    count_20       numeric(10, 2) NOT NULL,
    count_25       numeric(10, 2) NOT NULL,
    total_count    numeric(10, 2) NOT NULL,
    starting_year  BIGINT         NOT NULL,
    scheme_id      BIGINT         NOT NULL,
    CONSTRAINT pk_mf_return_stats PRIMARY KEY (id)
);

CREATE TABLE mf_scheme_details
(
    id            BIGINT       NOT NULL,
    scheme_code   VARCHAR(255) NOT NULL,
    scheme_name   VARCHAR(255) NOT NULL,
    category      VARCHAR(255) NOT NULL,
    sub_category  VARCHAR(255) NOT NULL,
    fund_house_id BIGINT       NOT NULL,
    CONSTRAINT pk_mf_scheme_details PRIMARY KEY (id)
);

CREATE TABLE mf_scheme_nav
(
    id              BIGINT  NOT NULL,
    nav_date        date    NOT NULL,
    net_asset_value numeric NOT NULL,
    scheme_id       BIGINT  NOT NULL,
    CONSTRAINT pk_mf_scheme_nav PRIMARY KEY (id)
);

ALTER TABLE mf_fund_house
    ADD CONSTRAINT uc_mf_fund_house_name UNIQUE (name);

ALTER TABLE mf_scheme_details
    ADD CONSTRAINT uc_mf_scheme_details_codename UNIQUE (scheme_code, scheme_name);

ALTER TABLE mf_return_stats
    ADD CONSTRAINT FK_MF_RETURN_STATS_ON_SCHEME FOREIGN KEY (scheme_id) REFERENCES mf_scheme_details (id);

ALTER TABLE mf_scheme_details
    ADD CONSTRAINT FK_MF_SCHEME_DETAILS_ON_FUND_HOUSE FOREIGN KEY (fund_house_id) REFERENCES mf_fund_house (id);

ALTER TABLE mf_scheme_nav
    ADD CONSTRAINT FK_MF_SCHEME_NAV_ON_SCHEME FOREIGN KEY (scheme_id) REFERENCES mf_scheme_details (id);