INSERT INTO mf_fund_house (name)
VALUES ('360 ONE Mutual Fund'),
       ('Aditya Birla Sun Life Mutual Fund'),
       ('Axis Mutual Fund'),
       ('Bajaj Finserv Mutual Fund'),
       ('Bandhan Mutual Fund'),
       ('Bank of India Mutual Fund'),
       ('Baroda BNP Paribas Mutual Fund'),
       ('Benchmark Mutual Fund'),
       ('Canara Robeco Mutual Fund'),
       ('DSP Mutual Fund'),
       ('Edelweiss Mutual Fund'),
       ('Franklin Templeton Mutual Fund'),
       ('Groww Mutual Fund'),
       ('HDFC Mutual Fund'),
       ('Helios Mutual Fund'),
       ('HSBC Mutual Fund'),
       ('ICICI Prudential Mutual Fund'),
       ('Invesco Mutual Fund'),
       ('ITI Mutual Fund'),
       ('JM Financial Mutual Fund'),
       ('Kotak Mahindra Mutual Fund'),
       ('LIC Mutual Fund'),
       ('Mahindra Manulife Mutual Fund'),
       ('Mirae Asset Mutual Fund'),
       ('Motilal Oswal Mutual Fund'),
       ('Navi Mutual Fund'),
       ('Nippon India Mutual Fund'),
       ('PGIM India Mutual Fund'),
       ('PPFAS Mutual Fund'),
       ('quant Mutual Fund'),
       ('Samco Mutual Fund'),
       ('SBI Mutual Fund'),
       ('Shriram Mutual Fund'),
       ('Sundaram Mutual Fund'),
       ('Tata Mutual Fund'),
       ('Taurus Mutual Fund'),
       ('Union Mutual Fund'),
       ('UTI Mutual Fund'),
       ('WhiteOak Capital Mutual Fund'),
       ('Zerodha Mutual Fund');
	